// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwSzBocMoNjBubCavV34Sf5gh2TASm2Ak',
    appId: '1:876265852052:web:25eba0bfc19ad73eae7881',
    messagingSenderId: '876265852052',
    projectId: 'karmik-24969',
    authDomain: 'karmik-24969.firebaseapp.com',
    storageBucket: 'karmik-24969.firebasestorage.app',
    measurementId: 'G-GK4842DCBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqzIApNHcDOwmZMWsF0e31GTvuSDexVGk',
    appId: '1:876265852052:android:6a2aaae649be7264ae7881',
    messagingSenderId: '876265852052',
    projectId: 'karmik-24969',
    storageBucket: 'karmik-24969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtDVhLYi7Ke0IjhL7-nqbvy5lhufo1UFM',
    appId: '1:876265852052:ios:9d273d619f6c7afdae7881',
    messagingSenderId: '876265852052',
    projectId: 'karmik-24969',
    storageBucket: 'karmik-24969.firebasestorage.app',
    iosBundleId: 'vedam.roots.expert.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDVhLYi7Ke0IjhL7-nqbvy5lhufo1UFM',
    appId: '1:876265852052:ios:60ebc90b5016b793ae7881',
    messagingSenderId: '876265852052',
    projectId: 'karmik-24969',
    storageBucket: 'karmik-24969.firebasestorage.app',
    iosBundleId: 'com.example.astroPartnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwSzBocMoNjBubCavV34Sf5gh2TASm2Ak',
    appId: '1:876265852052:web:ade1a15d1f4889baae7881',
    messagingSenderId: '876265852052',
    projectId: 'karmik-24969',
    authDomain: 'karmik-24969.firebaseapp.com',
    storageBucket: 'karmik-24969.firebasestorage.app',
    measurementId: 'G-LNESZ1CPTT',
  );

}